# Generated by Django 2.2.8 on 2020-01-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0035_ville_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
