# Generated by Django 2.2.4 on 2019-08-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=42)),
                ('presentation', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'liste',
                'ordering': ['nom'],
            },
        ),
    ]
