# Generated by Django 2.2.4 on 2019-08-31 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('criteres', models.ManyToManyField(related_name='Ville', to='compare.Critere')),
            ],
        ),
        migrations.CreateModel(
            name='promesse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('description', models.TextField(null=True)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Critere')),
            ],
        ),
        migrations.AddField(
            model_name='liste',
            name='promesses',
            field=models.ManyToManyField(to='compare.promesse'),
        ),
        migrations.AddField(
            model_name='liste',
            name='ville',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='compare.Ville'),
        ),
    ]
