# Generated by Django 2.2.4 on 2019-08-31 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0003_auto_20190831_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liste',
            name='promesses',
        ),
        migrations.AddField(
            model_name='promesse',
            name='liste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='compare.Liste'),
        ),
    ]
