# Generated by Django 2.2.4 on 2019-09-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_auto_20190831_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='promesse',
            name='estUnEngagement',
            field=models.BooleanField(default=False),
        ),
    ]
