# Generated by Django 2.2.4 on 2019-09-11 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compare', '0006_auto_20190911_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liste',
            name='auteur',
        ),
        migrations.AddField(
            model_name='liste',
            name='auteur',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
