# Generated by Django 2.2.4 on 2019-09-17 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0008_auto_20190912_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste',
            name='auteur',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
