# Generated by Django 2.2.4 on 2019-10-09 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0010_auto_20190923_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Ville')),
            ],
        ),
    ]
