# Generated by Django 2.2.4 on 2019-11-15 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0011_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compare.Ville'),
        ),
    ]
