# Generated by Django 2.2.4 on 2019-12-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0013_auto_20191210_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ville',
            old_name='name',
            new_name='nom',
        ),
    ]
