# Generated by Django 2.2.4 on 2019-12-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0014_auto_20191210_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promesse',
            old_name='estUnEngagement',
            new_name='estUnePriorite',
        ),
    ]
