# Generated by Django 2.2.4 on 2019-12-20 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0015_auto_20191219_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='slogan',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Priorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.IntegerField(null=True)),
                ('Promesse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Promesse')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Liste')),
            ],
        ),
    ]
