# Generated by Django 2.2.4 on 2019-12-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0016_auto_20191220_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Priorite',
        ),
    ]
