# Generated by Django 2.2.4 on 2019-12-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0017_delete_priorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ville',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
