# Generated by Django 2.2.4 on 2019-12-31 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0018_auto_20191229_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('EstTeteDeListe', models.BooleanField()),
                ('Liste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Liste')),
            ],
        ),
    ]
