# Generated by Django 2.2.4 on 2020-01-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0019_candidat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
