# Generated by Django 2.2.4 on 2020-01-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0020_ville_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='critere',
            name='estStandard',
            field=models.BooleanField(default=True),
        ),
    ]
