# Generated by Django 2.2.4 on 2020-01-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0021_critere_eststandard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
