# Generated by Django 2.2.4 on 2020-01-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0022_auto_20200104_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='departement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
