# Generated by Django 2.2.4 on 2020-01-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0023_auto_20200104_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='ProfessionMaire',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='ageMaire',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='nomMaire',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='prenomMaire',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='sexMaire',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
