# Generated by Django 2.2.4 on 2020-01-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0024_auto_20200104_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='ville',
            name='dateNaissanceMaire',
            field=models.DateField(null=True),
        ),
    ]
