# Generated by Django 2.2.4 on 2020-01-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0025_ville_datenaissancemaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
