# Generated by Django 2.2.8 on 2020-01-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0027_auto_20200105_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='site',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
