# Generated by Django 2.2.8 on 2020-01-11 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0028_liste_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='liste',
            name='couleur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='liste',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='liste',
            name='presentation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liste',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='liste',
            name='slogan',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='liste',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Ville'),
        ),
        migrations.AlterField(
            model_name='promesse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promesse',
            name='liste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compare.Liste'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='ProfessionMaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='ageMaire',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='dateNaissanceMaire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='departement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='nomMaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='prenomMaire',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='sexMaire',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
