# Generated by Django 2.2.8 on 2020-01-14 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0030_auto_20200114_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='Liste',
        ),
        migrations.AddField(
            model_name='liste',
            name='teteDeListe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compare.Candidat'),
        ),
    ]
