# Generated by Django 2.2.8 on 2020-01-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0031_auto_20200114_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='EstTeteDeListe',
        ),
        migrations.AlterField(
            model_name='liste',
            name='teteDeListe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
