# Generated by Django 2.2.8 on 2020-01-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0038_auto_20200121_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='liste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compare.Liste'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('ACC', 'Formulaire contact'), ('VSL', 'Ville sans liste'), ('VAL', 'Ville avec listes'), ('SIN', 'Singalement'), ('LST', 'Liste')], default='ACC', max_length=3),
        ),
    ]
