# Generated by Django 2.2.8 on 2020-01-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0039_auto_20200126_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='lienPhoto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
