# Generated by Django 2.2.8 on 2020-01-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0040_liste_lienphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste',
            name='lienPhoto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
